### ISSUE TITLE
Return FailureReason with BackgroundFetchFail event.

### ISSUE THREAD

**Issue by mugdhalakhani** [WICG/background-fetch#70] opened 2018-05-23 15:29 UTC
To distinguish the many reasons a fetch can fail.

**Comment by jakearchibald** [comment] 2018-06-04 13:28
An enum on the event seems like the right thing. But let's figure out the failure reasons:

Failures caused by the operation as a whole:

* Downloaded more than download total.
* Quota exceeded (feels like this should be a different thing).

Failures caused by a single fetch:

* POST request/response interrupted and therefore can't be retried.
* "Network error" types that we can't distinguish for security reasons: CORS, MIX, SSL.
* Looks like the resource changed between partial responses (eg etag changed).
* Non-ok status code.
* Unexpected partial response (unparsable `Content-Range`, or returned range is unexpected).

What am I missing?

If the error is related to a single fetch, we should provide the record too.

**Comment by mugdhalakhani** [comment] 2018-07-23 17:15
Sounds about right.
Here's what I have in code for the first category at present:
enum class BackgroundFetchReasonToAbort {
  NONE,
  CANCELLED_FROM_UI,
  ABORTED_BY_DEVELOPER,
  TOTAL_DOWNLOAD_SIZE_EXCEEDED,
  SERVICE_WORKER_UNAVAILABLE,
};

Quota exceeded can be added to this.
The rest look good, let's add a catchall UNKNOWN error, because the download manager does return this back to us sometimes.

**Comment by jakearchibald** [comment] 2018-07-26 14:16
This will be a string enum btw https://heycam.github.io/webidl/#dfn-enumeration-value.

I've started some of the plumbing around it.

**Comment by mugdhalakhani** [comment] 2018-07-31 15:04
Thanks. Should this also be exposed with the abort event?

**Comment by jakearchibald** [comment] 2018-07-31 15:42
I'm going to see if I can roll it into https://wicg.github.io/background-fetch/#ref-for-dom-backgroundfetchregistration-state.

Values could be something like `"pending"`, `"success"`, `"failure-abort"`, `"failure-quota"`, `"failure-invalid-response"` etc etc. That means you can check if the state starts `"failure-"` for all failure cases. What do you think?

**Comment by mugdhalakhani** [comment] 2018-07-31 16:18
This feels like like we're overloading one variable to work for another. There can be many reasons for failure, and having multiple states defined of the type failure-<reason> doesn't feel elegant. WDYT about adding failure_reason to BackgroundFetchRegistration, with the value set to none when the fetch hasn't completed or has completed in success state?

**Comment by jakearchibald** [comment] 2018-08-09 12:46
Fixed in 3f13703e1fcc1b052f0ce742011e5f127e5b164e

**Closed by jakearchibald** 2018-08-09 12:46 UTC
