### ISSUE TITLE
downloadTotal - total of what?

### ISSUE THREAD

**Issue by kenchris** [WICG/background-fetch#74] opened 2018-05-29 13:35 UTC
`downloadTotal` of `options` in

`const bgFetchJob = await registration.backgroundFetch.fetch(id, requests, options);`

refers to the total size in bytes of all requests I assume. But the name doesn't make that very clear, it could as well be the total amounts of download requests.

**Comment by jakearchibald** [comment] 2018-05-29 14:27
Dupe of #78.

**Closed by jakearchibald** 2018-05-29 14:27 UTC
