### ISSUE TITLE
if downloadTotal is a hint, maybe add Hint to the name?

### ISSUE THREAD

**Issue by kenchris** [WICG/background-fetch#78] opened 2018-05-29 13:43 UTC
In response to https://github.com/w3ctag/design-reviews/issues/279

`downloadTotalHint` vs `expectedDownloadTotalBytes` ?

**Comment by jakearchibald** [comment] 2018-05-29 13:53
It isn't really a hint anymore, as we'll stop the download if it exceeds the `downloadTotal`. I need to update the explainer for this.

**Comment by kenchris** [comment] 2018-05-29 13:56
`maxDownloadSize` ?

**Comment by jakearchibald** [comment] 2018-05-29 14:05
Yeah, I like that.

**Comment by jakearchibald** [comment] 2018-06-15 09:19
I think we need to stay away from "download" in this, since it's the total size of the response bodies. "download" seems to suggest bytes down the wire, which is different.

**Comment by jakearchibald** [comment] 2018-09-13 12:40
Dupe of #66

**Closed by jakearchibald** 2018-09-13 12:40 UTC
